"""
JSON Contracts for Multi-Agent Architecture.

All agents communicate via these strictly typed models.
This ensures deterministic, testable, and logged interactions.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime
from enum import Enum


class StepType(str, Enum):
    """Available execution steps."""
    SEARCH_WEB = "search_web"
    REASONING = "reasoning"
    SYNTHESIZE = "synthesize"


class AnalysisResult(BaseModel):
    """
    Output of Query Analyzer.
    Determines routing decisions for the orchestrator.
    """
    needs_web: bool = Field(
        description="Whether web search is required for this query"
    )
    needs_deep_reasoning: bool = Field(
        description="Whether heavy reasoning (external API) is required"
    )
    complexity_score: float = Field(
        ge=0.0, le=1.0,
        description="Estimated complexity of the query (0.0 = trivial, 1.0 = very complex)"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in this analysis (0.0 = uncertain, 1.0 = certain)"
    )
    reason: str = Field(
        description="Human-readable explanation of the routing decision"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "needs_web": True,
                "needs_deep_reasoning": True,
                "complexity_score": 0.85,
                "confidence": 0.92,
                "reason": "Requires recent data and multi-factor analysis"
            }
        }


class ExecutionPlan(BaseModel):
    """
    Execution plan generated by the planner.
    Contains ordered list of steps to execute.
    """
    steps: List[StepType] = Field(
        description="Ordered list of execution steps"
    )
    context: Dict[str, Any] = Field(
        default_factory=dict,
        description="Initial context for execution"
    )
    trace_id: Optional[str] = Field(
        default=None,
        description="Unique trace ID for logging"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "steps": ["search_web", "reasoning", "synthesize"],
                "context": {"query": "What is the economic impact of AI?"},
                "trace_id": "trace-abc123"
            }
        }


class WebSearchResult(BaseModel):
    """
    Result from SearXNG Web Agent.
    Contains structured facts and sources.
    """
    facts: List[str] = Field(
        description="Extracted factual statements"
    )
    sources: List[str] = Field(
        description="Source URLs"
    )
    raw_snippets: List[str] = Field(
        default_factory=list,
        description="Raw text snippets from search results"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in the quality of results"
    )
    query_used: str = Field(
        description="The actual query sent to search engine"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "facts": [
                    "Bitcoin price is $42,000 as of December 2024",
                    "Market cap exceeds $800 billion"
                ],
                "sources": [
                    "https://example.com/bitcoin-price",
                    "https://crypto.com/market"
                ],
                "raw_snippets": ["Bitcoin trading at..."],
                "confidence": 0.85,
                "query_used": "current bitcoin price USD"
            }
        }


class ReasoningResult(BaseModel):
    """
    Result from Groq Reasoning Agent.
    Contains formal structured reasoning output.
    """
    conclusion: str = Field(
        description="Main conclusion or answer"
    )
    reasoning_chain: List[str] = Field(
        default_factory=list,
        description="Step-by-step reasoning steps"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in the reasoning"
    )
    limitations: List[str] = Field(
        default_factory=list,
        description="Known limitations or assumptions"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "conclusion": "AI will likely increase productivity but displace some jobs",
                "reasoning_chain": [
                    "Historical precedent shows technology shifts...",
                    "Current AI capabilities suggest...",
                    "Economic models predict..."
                ],
                "confidence": 0.78,
                "limitations": ["Limited to available data up to 2024"]
            }
        }


class DecisionLogEntry(BaseModel):
    """
    Log entry for decision tracking.
    """
    trace_id: str = Field(description="Unique trace identifier")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    step_type: str = Field(description="Type of decision/step")
    input_data: Dict[str, Any] = Field(description="Input to this step")
    output_data: Dict[str, Any] = Field(description="Output from this step")
    duration_ms: Optional[float] = Field(default=None, description="Execution time in ms")
    
    class Config:
        json_schema_extra = {
            "example": {
                "trace_id": "trace-abc123",
                "timestamp": "2024-12-19T12:00:00Z",
                "step_type": "analysis",
                "input_data": {"query": "What is AI?"},
                "output_data": {"needs_web": False},
                "duration_ms": 15.2
            }
        }


class OrchestratorRequest(BaseModel):
    """
    Input to the Enhanced Orchestrator.
    """
    query: str = Field(description="User query to process")
    session_id: Optional[str] = Field(default=None, description="Session ID for context")
    force_web: bool = Field(default=False, description="Force web search regardless of analysis")
    force_reasoning: bool = Field(default=False, description="Force reasoning regardless of analysis")


class OrchestratorResponse(BaseModel):
    """
    Output from the Enhanced Orchestrator.
    """
    answer: str = Field(description="Final response to user")
    trace_id: str = Field(description="Trace ID for debugging")
    plan_executed: List[str] = Field(description="Steps that were executed")
    analysis: AnalysisResult = Field(description="Query analysis result")
    sources: List[str] = Field(default_factory=list, description="Sources used")
