"""Initial schema

Revision ID: 5ce7eea3e8c3
Revises: 
Create Date: 2025-12-17 16:47:25.954046+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce7eea3e8c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_memory_id'), 'audit_log', ['memory_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('config_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('idx_config_scope_effective', 'config_versions', ['scope', 'effective_from'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('ref_id', sa.JSON(), nullable=True),
    sa.Column('part_of_message_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_archived_false_created', 'memory_records', ['created_at'], unique=False, postgresql_where=sa.text('archived = false'))
    op.create_index('idx_channel_created', 'memory_records', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_memory_type_created', 'memory_records', ['memory_type', 'created_at'], unique=False)
    op.create_index('idx_source_created', 'memory_records', ['source', 'created_at'], unique=False)
    op.create_index(op.f('ix_memory_records_content_hash'), 'memory_records', ['content_hash'], unique=False)
    op.create_table('vector_mappings',
    sa.Column('faiss_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('full_vector', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_records.id'], ),
    sa.PrimaryKeyConstraint('faiss_id')
    )
    op.create_index('idx_vector_memory_id', 'vector_mappings', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_memory_id', table_name='vector_mappings')
    op.drop_table('vector_mappings')
    op.drop_index(op.f('ix_memory_records_content_hash'), table_name='memory_records')
    op.drop_index('idx_source_created', table_name='memory_records')
    op.drop_index('idx_memory_type_created', table_name='memory_records')
    op.drop_index('idx_channel_created', table_name='memory_records')
    op.drop_index('idx_archived_false_created', table_name='memory_records', postgresql_where=sa.text('archived = 0'))
    op.drop_table('memory_records')
    op.drop_index('idx_config_scope_effective', table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_memory_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
